<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>11</LangVersion>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <IsAotCompatible>true</IsAotCompatible>
    <NoWarn>$(NoWarn);RCS1090</NoWarn>
    <InvariantGlobalization>true</InvariantGlobalization>
    <EmccFlags>-s FULL_ES3=1 -s MIN_WEBGL_VERSION=2 -lopenal -lGL -s</EmccFlags>
    <WasmMainJSPath>main.js</WasmMainJSPath>
  </PropertyGroup>

  <PropertyGroup>
    <PublishTrimmed>true</PublishTrimmed>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <WasmBuildNative>true</WasmBuildNative>
    <RunAOTCompilation>true</RunAOTCompilation>
    <!-- Disable SIMD support as it's prerelease only on Safari -->
    <WasmEnableSIMD>false</WasmEnableSIMD>
    <!-- Normal,JustInterp,Full,FullInterp,Hybrid,LLVMOnly,LLVMOnlyInterp -->
    <!-- <AOTMode>LLVMOnly</AOTMode> -->
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Strawberry.Test\Strawberry.Test.csproj" />
    <ProjectReference Include="..\Strawberry.Web\Strawberry.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <NativeFileReference Include="Native/libEGL.c" ScanForPInvokes="true" />
    <NativeFileReference Include="Native/libGLESv3.c" ScanForPInvokes="true" />
    <NativeFileReference Include="Native/libopenal.c" ScanForPInvokes="true" />
    <NativeFileReference Include="Native/emscripten.c" ScanForPInvokes="true" />

    <WasmExtraFilesToDeploy Include="index.html" />
    <WasmExtraFilesToDeploy Include="main.js" />
    <WasmExtraFilesToDeploy Include="$(MSBuildThisFileDirectory)Assets\**"
      TargetPath="Assets/%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\" />
  </ItemGroup>

</Project>