<Project>
  <Target Name="CopyNativeAssets" AfterTargets="ResolveAssemblyReferences">
    <ItemGroup>
      <PackageContent Include="$(MSBuildThisFileDirectory)contentFiles\any\Native\**\*" />
    </ItemGroup>

    <Copy
      SourceFiles="@(PackageContent)"
      DestinationFolder="$(TargetDir)"
      SkipUnchangedFiles="true"
      OverwriteReadOnlyFiles="true"
    />
  </Target>
</Project>