<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Strawberry.Common\Strawberry.Common.csproj" />
    <ProjectReference Include="..\Strawberry\Strawberry.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Native\**\*">
      <Pack>true</Pack>
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>