<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-android</TargetFramework>
    <SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationId>com.companyname.Strawberry.Android.Test</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <!--
      Enables trim analyzers and full trimming during Release mode.
      To learn more, see:
    https://learn.microsoft.com/dotnet/core/deploying/trimming/trimming-options#trimming-granularity
    -->
    <TrimMode>full</TrimMode>
  </PropertyGroup>

  <PropertyGroup>
    <AndroidSdkDirectory>c:\work\android-sdk</AndroidSdkDirectory>
    <JavaSdkDirectory>c:\work\jdk</JavaSdkDirectory>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Strawberry.Android\Strawberry.Android.csproj" />
    <ProjectReference Include="..\Strawberry.Test\Strawberry.Test.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\" />
  </ItemGroup>
</Project>