<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-android</TargetFramework>
    <SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!--
      Enable trim analyzers for Android class libraries.
      To learn more, see:
    https://learn.microsoft.com/dotnet/core/deploying/trimming/prepare-libraries-for-trimming
    -->
    <IsTrimmable>true</IsTrimmable>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <PropertyGroup>
    <AndroidSdkDirectory>c:\work\android-sdk</AndroidSdkDirectory>
    <JavaSdkDirectory>c:\work\jdk</JavaSdkDirectory>
  </PropertyGroup>

  <ItemGroup>
    <None Include="android\**\*.so"
      Pack="true"
      PackagePath="android/" />

    <None Include="buildTransitive\Strawberry.OpenAL.targets"
      Pack="true"
      PackagePath="buildTransitive/" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Strawberry.OpenAL\Strawberry.OpenAL.csproj" />
    <ProjectReference Include="..\Strawberry\Strawberry.csproj" />
  </ItemGroup>
</Project>