<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Strawberry.Common\Strawberry.Common.csproj" />
    <ProjectReference Include="..\Strawberry.Physics\Strawberry.Physics.csproj" />

    <EmbeddedResource Include="Graphics\Text\Joinings.txt" />
    <EmbeddedResource Include="Graphics\Text\UnicodeDatabase.txt" />
  </ItemGroup>

</Project>