<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Strawberry\Strawberry.csproj" />
    <ProjectReference Include="..\Strawberry.OpenAL\Strawberry.OpenAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.9.4" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="runtimes\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Pack>true</Pack>
      <PackagePath>contentFiles\any\any\runtimes\</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <CopyToOutput>true</CopyToOutput>
    </Content>
  </ItemGroup>
</Project>