<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Strawberry.OpenAL\Strawberry.OpenAL.csproj" />
    <ProjectReference Include="..\Strawberry\Strawberry.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="native\emscripten.c"
      Pack="true"
      PackagePath="native/" />

    <None Include="native\libEGL.c"
      Pack="true"
      PackagePath="native/" />

    <None Include="native\libGLESv3.c"
      Pack="true"
      PackagePath="native/" />

    <None Include="native\libopenal.c"
      Pack="true"
      PackagePath="native/" />

    <None Include="buildTransitive\Strawberry.Web.targets"
      Pack="true"
      PackagePath="buildTransitive/" />

    <Content Include="wwwroot\**\*" CopyToOutputDirectory="PreserveNewest" Pack="true" PackagePath="contentFiles/any/any/wwwroot/" />
  </ItemGroup>

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>